 name: Waka Readme
  on:
    schedule:
      - cron: '30 18 * * *'
      # Runs at 12am IST
    workflow_dispatch:
  jobs:
    update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
        - name: Update Readme with Metrics
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
